-- V5 Supabase starter schema
create table profiles (id uuid primary key references auth.users(id) on delete cascade, company_id uuid not null, display_name text not null, role text not null check(role in ('owner','admin','worker')));
create table jobs (id bigint generated by default as identity primary key, company_id uuid not null, client text not null, phone text, type text, address text, work_date date, worker_id uuid references profiles(id), status text, amount numeric default 0, paid numeric default 0, note text, created_at timestamptz default now());
alter table profiles enable row level security;
alter table jobs enable row level security;
-- 上線前必須建立 company_id/auth.uid() 對應的 RLS policies。
-- job-photos 請使用 private Storage bucket 並建立 policies。
